{{- if .Values.addCluster }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.clusterName }}
  namespace: {{ .Values.namespace }}
  labels:
    argocd.argoproj.io/secret-type: cluster
    env_name: {{ .Values.env_name }}
type: Opaque
stringData:
  name: {{ .Values.clusterName }}
  server: https://{{ .Values.clusterFqdn }}
  config: |
    {
      "bearerToken": {{ .Values.clusterToken | quote }},
      "tlsClientConfig": {
        "insecure": false,
        "caData": {{ .Values.clusterCert | quote }}
      }
    }
{{- end }}