name: istio-ingressgateway-backend-canary
 
replicaCount: 2
 
serviceAccount:
  name: istio-ingressgateway-canary-backend-sa

service:
  type: LoadBalancer
  ports:
  - name: status-port
    port: 15020
    targetPort: 15020
    protocol: TCP
  - name: http2
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    port: 443
    targetPort: 8443
    protocol: TCP
 
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 5
 
labels:
  app: istio-ingressgateway-backend-canary
  istio: ingressgateway-backend-canary
 
 
 