name: istio-ingressgateway
 
replicaCount: 2
 
serviceAccount:
  name: istio-ingressgateway-sa
 
  service:
    # Type of service. Set to "None" to disable the service entirely
    type: LoadBalancer
    ports:
    - name: status-port
      port: 15020
      protocol: TCP
      targetPort: 15020
    - name: http2
      port: 80
      protocol: TCP
      targetPort: 80
    - name: https
      port: 443
      protocol: TCP
      targetPort: 443

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 3
 
labels:
  app: istio-ingressgateway
  istio: ingressgateway
 