apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: apps3
  namespace: argocd
  # labels:
  #   applicationset: app-test1
  #   app: app-test1
    #environment: '{{.metadata.labels.env_name}}'
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  source:
    path: ArgoCD/apps3
    repoURL: 'https://github.com/wiktorvip/k8s-lab-argocd'
    targetRevision: HEAD
  project: "default"
  syncPolicy:
    syncOptions:
      - CreateNamespace=false
    automated:
      prune: false
      selfHeal: false
