apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: default
  source:
    - repoURL: https://github.com/wiktorvip/k8s-lab-argocd
      targetRevision: main
      ref: values

    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      #path: argo-cd
      targetRevision: 7.8.0
      helm:
        releaseName: argocd
        valueFiles:
          - $values/ArgoCD/values/values.yaml
  destination:
    name: in-cluster
    namespace: argocd
  syncPolicy:
    # automated:
    #   prune: false
    #   selfHeal: true
    syncOptions:
      - CreateNamespace=true
