apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
  labels:
    applicationset: metallb
    app: 'metallb'
    environment: '{{.metadata.labels.env_name}}'
spec:
  project: default
  sources:
    - repoURL: https://github.com/wiktorvip/k8s-lab-argocd
      targetRevision: main
      ref: values

    - repoURL: https://metallb.github.io/metallb
      chart: metallb
      targetRevision: 0.14.6
      helm:
        releaseName: metallb
        valueFiles:
          - $values/metallb/values/values.yaml
  ignoreDifferences:
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: bgppeers.metallb.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
    - group: "apiextensions.k8s.io"
      kind: CustomResourceDefinition
      name: addresspools.metallb.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
  destination:
    name: in-cluster
    namespace: metallb-system
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - CreateNamespace=true
      - RespectIgnoreDifferences=true

