apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: metrics-server
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - clusters:
        selector:
          # matchLabels:
          #   env_name: 'dev'
          matchExpressions:
            - {key: ingress-nginx, operator: DoesNotExist}            
 
  template:
    metadata:
      name: 'metrics-server-{{.name}}'
      labels:
        applicationset: metrics-server
        app: 'metrics-server'
        environment: '{{.metadata.labels.env_name}}'
        #region: '{{.metadata.labels.location}}'
    spec:
      project: "default"
      sources:
        - repoURL: https://github.com/wiktorvip/k8s-lab-argocd
          targetRevision: main
          ref: values

        - repoURL: https://kubernetes-sigs.github.io/metrics-server
          chart: metrics-server
          targetRevision: 3.12.1
          helm:
            releaseName: metrics-server
            valueFiles:
              - $values/metrics-server/values/values.yaml
      destination:
        server: '{{.server}}'
        namespace: metrics-server
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: false
          selfHeal: true
  syncPolicy:
    preserveResourcesOnDeletion: true
    automated:
      prune: false
      selfHeal: true

