apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nfs-subdir-external-provisioner
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - clusters:
        selector:
          # matchLabels:
          #   env_name: 'dev'
          matchExpressions:
            - {key: ingress-nginx, operator: DoesNotExist}            
 
  template:
    metadata:
      name: 'nfs-subdir-external-provisioner-{{.name}}'
      labels:
        applicationset: nfs-subdir-external-provisioner
        app: 'nfs-subdir-external-provisioner'
        environment: '{{.metadata.labels.env_name}}'
        #region: '{{.metadata.labels.location}}'
    spec:
      project: "default"
      sources:
        - repoURL: https://github.com/wiktorvip/k8s-lab-argocd
          targetRevision: main
          ref: values

        - repoURL: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
          chart: nfs-subdir-external-provisioner
          targetRevision: 4.0.18
          helm:
            releaseName: nfs-subdir-external-provisioner
            valueFiles:
              - $values/nfs-subdir-external-provisioner/values/values.yaml
      destination:
        server: '{{.server}}'
        namespace: nfs-storage
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
        automated:
          prune: false
          selfHeal: true
  syncPolicy:
    preserveResourcesOnDeletion: true
    automated:
      prune: false
      selfHeal: true

