apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    app: app-webcolor-blue
spec:
  type: ClusterIP
  selector:
    app: app-webcolor-blue
  ports:
    - port: {{.Values.port}}
      targetPort: 9000