apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: istio-ingressgw-backend
  namespace: gemz
spec:
  goTemplate: true
  generators:
    - clusters:
        selector:
          matchLabels:
            env_name: 'dev'    
          matchExpressions:
            - {key: ingress-nginx, operator: DoesNotExist}
        values:
          istioVersion: 1.24.3
          istioRevision: 1-24-3

  template:
    metadata:
      name: 'istio-ingressgw-backend-{{.name}}'
      labels:
        applicationset: istio-ingressgw-backend
        app: 'istio-install'
        environment: '{{.metadata.labels.env_name}}'
        #region: '{{.metadata.labels.location}}'
    spec:
      project: "default"
      sources:
        - repoURL: https://github.com/wiktorvip/k8s-lab-argocd
          targetRevision: 'main'
          ref: values
 
        - repoURL: https://istio-release.storage.googleapis.com/charts
          chart: gateway
          targetRevision: '{{.values.istioVersion}}'
          helm:
            values: |
              revision: {{.values.istioRevision}}
            valueFiles:
              - $values/ServiceMesh/istio-install/{{.metadata.labels.env_name}}/{{.name}}/istio-ingressgateway-backend-values.yaml
      destination:
        server: '{{.server}}'
        namespace: istio-system
      syncPolicy:
        syncOptions:
          - CreateNamespace=true
  syncPolicy:
    preserveResourcesOnDeletion: true
 